# Generated by Django 5.2 on 2025-04-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_contact_alter_customuser_first_name_and_more'),
    ]

    operations = [
    ]
