# Generated by Django 5.2 on 2025-04-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_update_gender_values'),
    ]

    operations = [
    ]
