# Generated by Django 5.2 on 2025-05-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
